;-------------------------------------------------------------------
; 32-bit Keyboard functionality.
;-------------------------------------------------------------------

GLOBAL wait_VBLANK:PROC
GLOBAL setVideoMode:PROC
GLOBAL drawDot:PROC
GLOBAL drawRectangle:PROC
GLOBAL drawFilledRectangle:PROC
GLOBAL fillBackground:PROC
GLOBAL ReadFile:PROC
GLOBAL DrawIMG:PROC
GLOBAL DrawBG:PROC
GLOBAL randBetweenVal:PROC
GLOBAL rand:PROC
GLOBAL isInInterval:PROC
GLOBAL collision:PROC
GLOBAL waitForSpecificKeystroke:PROC
GLOBAL terminateProcess:PROC


;-------------------------------------------------------------------
; Scancodes
;   see: http://www.ee.bgu.ac.il/~microlab/MicroLab/Labs/ScanCodes.htm
;-------------------------------------------------------------------
